<?php
$pageTitle = "ভেষজ উন্নয়ন ফাউন্ডেশন";
include __DIR__ . "/includes/header.php";
?>
<section class="hero"><div class="hero-content"><div><span class="eyebrow">স্বেচ্ছাসেবী ও সেবামূলক প্রতিষ্ঠান</span><h1>প্রকৃতির শক্তিতে<br><span>সুস্থ ও সুন্দর বাংলাদেশ</span></h1><p>ভেষজ জ্ঞান, পরিবেশ সংরক্ষণ ও মানবসেবার মাধ্যমে একটি সুস্থ সমাজ গড়ে তোলাই আমাদের অঙ্গীকার।</p><div class="hero-actions"><a href="#about" class="btn btn-primary">আমাদের সম্পর্কে জানুন</a><a href="donate.php" class="btn btn-light">Donation করুন</a></div></div><div class="hero-card"><img src="assets/images/foundation-logo.jpg" alt="ভেষজ উন্নয়ন ফাউন্ডেশন"></div></div></section>
<section class="stats"><div class="container stats-grid"><div><strong>১৫৪০/১৫</strong><span>নিবন্ধন নাম্বার</span></div><div><strong>সেবামূলক</strong><span>মানবিক কার্যক্রম</span></div><div><strong>ভেষজ</strong><span>উন্নয়ন ও সচেতনতা</span></div><div><strong>সবুজ</strong><span>পরিবেশ রক্ষা</span></div></div></section>
<section class="section" id="about"><div class="container two-col"><div><div class="section-heading"><span>আমাদের পরিচিতি</span><h2>ভেষজ উন্নয়ন ফাউন্ডেশন</h2></div><p>ভেষজ উন্নয়ন ফাউন্ডেশন একটি স্বেচ্ছাসেবী, সেবামূলক ও সামাজিক উন্নয়নমূলক প্রতিষ্ঠান। ভেষজ সম্পদ সংরক্ষণ, মানুষের মাঝে স্বাস্থ্য ও পরিবেশ সচেতনতা বৃদ্ধি এবং মানবিক সেবামূলক কার্যক্রম পরিচালনা আমাদের প্রধান লক্ষ্য।</p><p>আমরা বিশ্বাস করি, প্রকৃতি ও মানুষের মধ্যে সঠিক সম্পর্ক গড়ে উঠলে একটি সুস্থ, সচেতন ও টেকসই সমাজ তৈরি করা সম্ভব।</p></div><div class="about-image"><img src="assets/images/media-banner.jpg" alt="ফাউন্ডেশনের কার্যক্রম"></div></div></section>
<section class="section soft-bg" id="activities"><div class="container"><div class="section-heading center"><span>আমাদের কার্যক্রম</span><h2>মানুষ ও প্রকৃতির কল্যাণে</h2></div><div class="cards"><article class="info-card"><div class="icon">🌿</div><h3>ভেষজ উন্নয়ন</h3><p>দেশীয় ভেষজ উদ্ভিদ সংরক্ষণ, পরিচিতি ও সঠিক ব্যবহারের বিষয়ে সচেতনতা তৈরি।</p></article><article class="info-card"><div class="icon">🤝</div><h3>মানবিক সেবা</h3><p>সমাজের অসহায় ও প্রয়োজনীয় মানুষের পাশে দাঁড়ানোর জন্য সেবামূলক উদ্যোগ।</p></article><article class="info-card"><div class="icon">🌱</div><h3>পরিবেশ রক্ষা</h3><p>বৃক্ষরোপণ, সবুজায়ন এবং পরিবেশ সংরক্ষণে জনসম্পৃক্ত কার্যক্রম।</p></article></div></div></section>
<section class="section" id="message"><div class="container message-wrap"><div class="person-photo"><img src="assets/images/chairman.png" alt="প্রতিষ্ঠানের প্রতিনিধি"></div><div><div class="section-heading"><span>প্রতিষ্ঠানের বার্তা</span><h2>মানবসেবাই আমাদের অঙ্গীকার</h2></div><blockquote>“ভেষজ সম্পদ, সুস্থ জীবন ও মানবিক মূল্যবোধ—এই তিনটি বিষয়কে সামনে রেখে আমরা একটি সুন্দর ও সচেতন সমাজ গঠনে কাজ করে যেতে চাই।”</blockquote><p class="person-name">ভেষজ উন্নয়ন ফাউন্ডেশন</p></div></div></section>
<section class="section"><div class="container"><div class="section-heading center"><span>সংবাদ ও কার্যক্রম</span><h2>আমাদের মিডিয়া উপস্থিতি</h2></div><div class="media-frame"><img src="assets/images/media-banner.jpg" alt="সংবাদে ভেষজ উন্নয়ন ফাউন্ডেশন"></div></div></section>
<section class="contact-section" id="contact"><div class="container contact-grid"><div><span class="eyebrow">যোগাযোগ</span><h2>আমাদের সাথে যোগাযোগ করুন</h2><p>আপনার যেকোনো তথ্য, পরামর্শ বা সহযোগিতার জন্য আমাদের সাথে যোগাযোগ করতে পারেন।</p></div><div class="contact-box"><a href="tel:01913801181">📞 <span>কল করুন</span><strong>01913801181</strong></a><a href="https://wa.me/8801913801181" target="_blank">📲 <span>WhatsApp</span><strong>মেসেজ পাঠান</strong></a><div class="reg">নিবন্ধন নাম্বার: <b>১৫৪০/১৫</b></div></div></div></section>
<?php include __DIR__ . "/includes/footer.php"; ?>
